[project]
name = "aoc-2025"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "rbpatt2019", email = "rb.patterson.cross@gmail.com" }]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
aoc-2025 = "aoc_2025:main"

[project.optional-dependencies]
build = ["uv>=0.11.31,<0.12.0"]

[dependency-groups]
dev = [
  "python-semantic-release>=10.6.1,<11.0.0",
  "ruff>=0.15.22,<1.0.0",
  "ty>=0.0.63,<0.1.0",
]

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
source-include = ["tests/**"]

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py314"

[tool.ruff.lint]
include = ["ANN", "B", "C4", "C90", "D", "DOC", "F", "I", "RET", "RUF", "S"]

[tool.ruff.lint.mccabe]
max-complexity = 5

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
build_command = """
    python -m pip install -e .[build]
    uv lock --upgrade-package "$PACKAGE_NAME"
    git add uv.lock
    uv build
"""
commit_parser = "conventional"

[tool.semantic_release.changelog]
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = [
  '''chore(?:\([^)]*?\))?: .+''',
  '''ci(?:\([^)]*?\))?: .+''',
  '''refactor(?:\([^)]*?\))?: .+''',
  '''style(?:\([^)]*?\))?: .+''',
  '''test(?:\([^)]*?\))?: .+''',
  '''build\((?!deps\): .+)''',
  '''Initial [Cc]ommit.*''',
]
