[project]
name = "aoc-2025"
version = "0.0.0"
description = "AOC 2025"
readme = "README.md"
authors = [{ name = "rbpatt2019", email = "rb.patterson.cross@gmail.com" }]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
aoc-2025 = "aoc_2025:main"

[project.optional-dependencies]
build = ["certifi>=2026.7.22", "uv>=0.12.15"]

[dependency-groups]
dev = ["ruff>=0.15.22,<1.0.0", "ty>=0.0.63,<0.1.0"]

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
source-include = ["static/**"]

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py314"

[tool.ruff.lint]
select = ["ANN", "B", "C4", "C90", "D", "F", "I", "RET", "RUF", "S"]

[tool.ruff.lint.per-file-ignores]
"src/aoc_2025/base_class.py" = ["D102"]

[tool.ruff.lint.mccabe]
max-complexity = 5

[tool.ruff.lint.pydocstyle]
convention = "google"
